global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost']
  - job_name: 'flower'
    static_configs:
      - targets: ['draft2digital-staging-flower-t.herokuapp.com']
    basic_auth:
      username: 'admin'
      password: 'password'
